id: P429445A5
initial_creation_type: ocr
source_metadata:
  volumes:
    d22ef681fe404a178b8706f77e7089dd:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: འཕགས་པ་ཀུན་ནས་སྒོར་འཇུག་པའི་འོད་ཟེར་གཙུག་ཏོར་དྲི་མ་མེད་པར་སྣང་བའི་གཟུངས་བཀླག་ཅིང་མཆོད་རྟེན་བརྒྱ་རྩ་བརྒྱད་དམ།
        མཆོད་རྟེན་ལྔ་གདབ་པའི་ཆོ་ག་མདོ་སྡེ་ལས་བསྡུས་པ།
      total_pages: 1044
      volume_number: 38
